version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:latest
    environment:
      R_LIBS: ~/R/Library
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-{{ arch }}-
      - checkout
      - run:
          name: Install package dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgsl-dev
            mkdir -p ~/R/Library
            Rscript -e 'install.packages(c("devtools","Rcpp","RcppArmadillo","RcppParallel","MBSP","mvtnorm","matrixStats","testthat","varbvs","Rfast"))'
            Rscript -e 'devtools::install_github("stephenslab/ebnm",upgrade="never",force=TRUE)'
            Rscript -e 'devtools::install_github("stephenslab/mashr",upgrade="never",force=TRUE)'
            Rscript -e 'devtools::install_github("willwerscheid/flashier",upgrade="never",force=TRUE)'
      - run:
          name: Session information and installed package versions
          command: |
            Rscript -e 'sessionInfo()'
            Rscript -e 'installed.packages()[, c("Package", "Version")]'
            Rscript -e 'rmarkdown::pandoc_version()'
      - run:
          name: Build package
          command: R CMD build --no-build-vignettes --no-manual .
      - run:
          name: Check package
          no_output_timeout: 55m
          command: R CMD check --as-cran --ignore-vignettes --no-manual *tar.gz
      - store_artifacts:
          path: mr.mash.alpha.Rcheck/
      - save_cache:
          key: r-pkg-cache-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"
